# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Set up our JDK environment
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          check-latest: true

      # Build artifacts
      - name: Build apk
        id: buildAllApks
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Upload our APK
        uses: joabalea/App-Center-action@v1.0.2
        with:
          command: appcenter distribute stores publish -s Alpha -f app/build/outputs/apk/debug/app-debug.apk -r releaseNote -a user/app
          token: ${{secrets.APP_CENTER_TOKEN}}

